services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    hostname: raspberry
    environment:
      - TS_EXTRA_ARGS=--advertise-tags=tag:server --accept-dns=true
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_HOSTNAME=raspberry
      - TS_DEST_IP=
    env_file:
      - .env.tailscale
    volumes:
      - /var/lib/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=weblatex
    env_file:
      .env.mariadb
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 15s
      interval: 60s
      timeout: 5s
      retries: 3
  weblatex:
    image: weblatex
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/weblatex:/app/weblatex/compiler_workspace
    env_file:
      - .env.weblatex
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      - FTLCONF_webserver_port=8080
    volumes:
      - '/etc/pihole:/etc/pihole'
    network_mode: host
    restart: unless-stopped
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    network_mode: host
    restart: unless-stopped
    depends_on:
      weblatex:
        condition: service_started
